[package]
name = "kali-error"
version = "0.1.0"
edition = "2021"

[dependencies]
ariadne = "0.4"
pathdiff = "0.2"
thiserror = "1.0"


kali-parse = { path = "../kali-parse" }
kali-type = { path = "../kali-type" }
