[package]
name = "kali-codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
kali-ir = { path = "../kali-ir" }
kali-ast = { path = "../kali-ast" }

cranelift = "0.110"
cranelift-module = "0.110"
cranelift-native = "0.110"
cranelift-jit = "0.110"
